var poses = {quads:["Saddle", "Lizard", "Half Saddle", "Twisted Lizard"],
  hamstrings:["Seated Forward Fold", "Standing Straddle", "Half Front Split", "Dragon"],
  hips:["Pigeon", "Seated Cross Shin", "Bound Angle"],
  lowerBack:["Single Leg Forward Fold", "Puppy Dog", "Single Leg Forward Fold with QLT", "Sphinx"],
  upperBack:["Saddle Eagle", "Saddle Archer", "Standing Forward Fold with Interlacing Fingers"],
  shoulders:["Child's Pose with Shoulders", "Twisted Cross", "Thread the Needle"],
};

var links = {"Saddle" : 'img/saddle.png',
"Lizard" : 'img/lizard.jpg',
"Half Saddle" : , 
"Twisted Lizard" : ,
"Seated Forward Fold" : 'img/seated_forward_fold.jpg',
"Standing Straddle" : 'img/standing_straddle.jpg',
"Half Front Split" : ,
"Dragon" : ,
"Pigeon" : 'img/pigeon.jpg',
"Seated Cross Shin" : 'img/seated_cross_shin.jpg',
"Bound Angle" : ,
"Single Leg Forward Fold" : 'img/single_leg_forward_fold.png',
"Puppy Dog" : 'img/puppy_dog.jpg',
"Single Leg Forward Fold with QLT" : ,
"Sphinx" : ,
"Saddle Eagle" : ,
"Saddle Archer" : ,
"Standing Forward Fold with Interlacing Fingers" : ,
"Child's Pose with Shoulders" : ,
"Twisted Cross" : ,
"Thread the Needle" : }
